# Generated by Django 5.2.4 on 2025-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                default="default.jpg", upload_to="media/banner_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="male-avatar.png", upload_to="media/profile_pics/"
            ),
        ),
    ]
