# Generated by Django 5.2.4 on 2025-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                default="media/banner_pics/default.jpg", upload_to="media/banner_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="media/profile_pics/male-avatar.png",
                upload_to="media/profile_pics/",
            ),
        ),
    ]
