# Generated by Django 5.2.4 on 2025-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profile_pics/male-avatar.png", upload_to="profile_pics/"
            ),
        ),
    ]
