# Generated by Django 5.2.4 on 2025-08-18 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
