# Generated by Django 5.2.4 on 2025-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_due_date_task_due_time_task_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_completed",
            new_name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_time",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
